language: node_js
node_js:
  - "8"
dist: trusty
cache:
  yarn: true
  directories:
    - node_modules

before_script:
  - export DISPLAY=:99.0
  - export LIGHTHOUSE_CHROMIUM_PATH="$(pwd)/chrome-linux/chrome"
  - sh -e /etc/init.d/xvfb start
  - curl -L https://raw.githubusercontent.com/GoogleChrome/lighthouse/master/lighthouse-core/scripts/download-chrome.sh | bash

script:
  - yarn prettier-check
  - yarn lint
  - yarn run export
  - yarn test
